name: UltimateShout
version: ${version}
main: nl.chimpgamer.ultimateshout.UltimateShout
softdepend: [PlaceholderAPI, Vault]
authors: [ChimpGamer]
api-version: '1.13'

commands:
  shout:
    permission: ultimateshout.shout.use

permissions:
  ultimateshout.shout.use:
    default: op
  ultimateshout.shout.nocooldown:
    default: op
  ultimateshout.shout.reload:
    default: op